### ISSUE TITLE
Unable to find via composer require

### ISSUE THREAD

**Issue by Dr-Nio** [chrisbaltazar/PHP-DBConn-Library#2]
Hello Chrisbaltazar,
I am getting the error shown below, when trying to composer require this package in my CLI.
InvalidArgumentException                                                                                                                                                            
Could not find a matching version of package chrisbaltazar/dbconn. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by chrisbaltazar** [comment]
sorry I come back to you this late, seems to be solved now, you can see it directly from packagist now. Cheers
https://packagist.org/packages/chrisbaltazar/dbconn
